//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hamlatot
    {
        public int Id { get; set; }
        public string DateOfHamlata { get; set; }
        public string DateOfTakser { get; set; }
    }
}
