//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeerTableEntities : DbContext
    {
        public DeerTableEntities()
            : base("name=DeerTableEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<Diseases> Diseases { get; set; }
        public virtual DbSet<Hamlatot> Hamlatot { get; set; }
        public virtual DbSet<Vaccinations> Vaccinations { get; set; }
    }
}
