//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccinations
    {
        public int Id { get; set; }
        public string DateOfVaccination { get; set; }
        public string Medicine { get; set; }
        public string NextVaccinationDate { get; set; }
    }
}
